def quiz():
    """
    Generates module 1 quiz
    outputs print statements
    user needs to type and line execute each answer before the next question shows up
    """
    
    print("Module 3 Quiz (3 questions)")
    print()
    #Question 1
    print("Question 1: When water is moving out of the estuary towards the ocean-what is this called?")
    print()
    print("a. Ebb")
    print("b. Flood")
    print("c. Slack")
    answer = input("Make your choice: ")
    if answer.lower() == "a":
        print("Correct!")
    else:
        print("Incorrect")
    
    #Question 2    
    print("Question 2: What is a current generated by the difference in sea surface elevation between different locations?")
    print()
    print("a. Ebb")
    print("b. Surface Tilt")
    print("c. Tidal Currents")
    answer = input("Make your choice: ")
    if answer.lower() == "c":
        print("Correct!")
    else:
        print("Incorrect") 
    #Question 3
    print("Question 3: What are tidal currents stages?")
    print()
    print("a. New, Third Quarter, Full, First")
    print("b. Ebb, Flood, Slack")
    print("c. Ocean, Estuary")
    answer = input("Make your choice: ")
    if answer.lower() == "b":
        print("Correct!")
    else:
        print("Incorrect") 
    